# needforheat-analysis/analysis/utils/__init__.py

from .nfh_metrics import mae, rmse, rmae

from .nfh_constants import (
    s_min_1, min_h_1, h_d_1, d_a_1, s_h_1, s_d_1, s_a_1,
    J_kWh_1, J_MJ_1, ml_m_3, dm3_m_3, umol_mol_1,
    cm2_m_2, temp_0__degC__K, P_std__Pa,
    R__m3_Pa_K_1_mol_1, 
    air_density__kg_m_3, air_specific_heat_capacity__J_kg__1_K_1, air_specific_heat_capacity__J_mol__1_K_1, air_volumetric_specific_heat_capacity__J_m__3_K_1,
    temp_room_std__degC, temp_gas_std__degC, temp_gas_std__K,
    temp_room_std__K, gas_room__mol_m_3,
    temp_gas_ref__degC, temp_gas_ref__K, 
    gas_std__mol_m_3, co2_outdoor_eu_avg_2022__ppm,
    air_std__J_mol_K, air_room__J_mol_K,
    air_std__J_m_3_K_1, air_room__J_m_3_K_1,
    g__m_s_2,
    water_density__kg_dm_3, water_specific_heat_capacity__J_kg_1_K_1, water_volumetric_heat_capacity__J_dm_3_K_1, 
    steel__J_kg_1_K_1,
    O2ml_min_1_kg_1_p_1_MET_1, desk_work__MET, sedentary__MET, 
    metabolism__molCO2_molO2_1, adult_weight_nl_avg__kg,
    O2umol_s_1_p_1_MET_1, co2_exhale_desk_work__umol_p_1_s_1, co2_exhale_sedentary__umol_p_1_s_1,
    gas_groningen_nl_avg_std_hhv__J_m_3, gas_groningen_nl_avg_std_lhv__J_m_3,
    co2_wtw_groningen_gas_std_nl_avg_2024__g__m_3, co2_wtw_e_onbekend_nl_avg_2024__g__kWh_1,
    overpressure_gas_nl_avg__Pa, temp_gas_nl_avg__degC, temp_gas_nl_avg__K,
    gas_g25_3_ref_lhv__J_m_3, gas_g25_3_ref_hhv__J_m_3,
    household_nl_avg__p, 
    asleep_at_home_nl_avg__h_d_1, awake_at_home_nl_avg__h_d_1,
    at_home_nl_avg__h_d_1, away_from_home_nl_avg, 
    occupancy_nl_avg__p,
    heat_awake_int_nl_avg__W_p_1, heat_asleep_int_nl_avg__W_p_1, 
    heat_int_present_nl_avg__W_p_1, heat_int_nl_avg__W_p_1,
    eta_ch_nl_avg_hhv__W0, g_not_ch_nl_avg__m3_a_1, g_not_ch_nl_avg_hhv__W,
    heat_tr_bldng_nl_avg__W_K_1, th_inert_bldng_nl_avg__h, th_mass_bldng_nl_avg__Wh_K_1,
    aperture_sol_nl_avg__m2,
    floor_single_home_dwelling_nl_avg__m2,
    heat_dstr_nl_avg_abs__Pa,
    heat_tr_dstr_nl_avg__W_K_1, th_mass_dstr_nl_avg__Wh_K_1, 
    max_dstr_flow_nl_avg__m3_h_1, pump_speed_flow_ratio_nl_avg__kg_s_1_pct_1, 
    temp_indoor_heating_season_nl_avg__degC, temp_outdoor_heating_season_nl_avg__degC, delta_temp_heating_season_nl_avg__K,
    P_nl_avg__Pa,
    wind_chill_nl_avg__K_s_m_1, aperture_inf_nl_avg__cm2,
    g_use_cooking_nl_avg__m3_a_1, g_use_cooking_nl_avg_hhv__W, eta_cooking_nl_avg_hhv__W0, frac_remain_cooking_nl_avg__0, 
    g_use_dhw_nl_avg__m3_a_1, g_use_dhw_nl_avg_hhv__W, eta_dhw_nl_avg_hhv__W0, frac_remain_dhw_nl_avg__0, 
    eta_not_ch_nl_avg_hhv__W0
)