# needforheat-analysis/analysis/__init__.py

from .nfh_utils import (
    mae, rmse, rmae,
    s_min_1, min_h_1, h_d_1, d_a_1, s_h_1, s_d_1, s_a_1,
    J_kWh_1, J_MJ_1, ml_m_3, dm3_m_3, umol_mol_1,
    cm2_m_2, temp_0__degC__K, P_std__Pa,
    R__m3_Pa_K_1_mol_1, temp_room_std__degC,
    temp_gas_std__degC, temp_gas_std__K,
    temp_room_std__K, gas_room__mol_m_3,
    temp_gas_ref__degC, temp_gas_ref__K, 
    gas_std__mol_m_3, co2_ext_eu_avg_2022__ppm,
    air_std__J_mol_K, air_room__J_mol_K,
    air_std__J_m_3_K_1, air_room__J_m_3_K_1,
    O2ml_min_1_kg_1_p_1_MET_1, desk_work__MET,
    metabolism__molCO2_molO2_1, adult_weight_nl_avg__kg,
    O2umol_s_1_p_1_MET_1, co2_exhale_desk_work__umol_p_1_s_1,
    gas_groningen_nl_avg_std_hhv__J_m_3, gas_groningen_nl_avg_std_lhv__J_m_3,
    overpressure_gas_nl_avg__Pa, temp_gas_avg_nl__degC, temp_gas_avg_nl__K, 
    gas_g25_3_ref_lhv__J_m_3, gas_g25_3_ref_hhv__J_m_3,
    household_nl_avg__p, 
    asleep_at_home_nl_avg__h_d_1, awake_at_home_nl_avg__h_d_1,
    at_home_nl_avg__h_d_1, away_from_home_nl_avg, 
    occupancy_nl_avg__p,
    Q_gain_awake_int_nl_avg__W_p_1, Q_gain_asleep_int_nl_avg__W_p_1, 
    Q_gain_int_present_nl_avg__W_p_1, Q_gain_int_nl_avg__W_p_1,
    eta_ch_nl_avg_hhv__W0, g_not_ch_nl_avg__m3_a_1, g_not_ch_nl_avg_hhv__W,
    H_nl_avg__W_K_1, tau_nl_avg__h, C_avg_nl__kWh_K_1,
    A_sol_nl_avg__m2,
    floor_single_home_dwelling_nl_avg__m2,
    H_dist_nl_avg__W_K_1, C_dist_nl_avg__J_K_1, 
    temp_in_heating_season_nl_avg__degC, temp_out_heating_season_nl_avg__degC, delta_temp_heating_season_nl_avg__K,
    P_nl_avg__Pa,
    wind_chill_nl_avg__K_s_m_1, A_inf_nl_avg__cm2,
    g_use_cooking_nl_avg__m3_a_1, g_use_cooking_nl_avg_hhv__W, eta_cooking_nl_avg_hhv__W0, frac_remain_cooking_nl_avg__0, 
    g_use_dhw_nl_avg__m3_a_1, g_use_dhw_nl_avg_hhv__W, eta_dhw_nl_avg_hhv__W0, frac_remain_dhw_nl_avg__0, 
    eta_not_ch_nl_avg_hhv__W0
)
